### ISSUE TITLE
Update to OpenCV 4.x and CUDA 10.1

### ISSUE THREAD

**Issue by philippoertle** [adrelino/variational-depth-from-focus#5]
Hi Adrelino,

I successfully used your VDFF code to analyze some data I recorded with a low-focus-depth optics - thanks for sharing the code, it works really well! I managed to compile your code as described on ubuntu 14.04, opencv 2.4.x and cuda 7. Because my knowledge of cuda/c++ is very limited, I don't manage to make your code compile for newer systems (Ubuntu 16.04, openCV 4.0.1 and CUDA 10.1). Do you plan to update your code at some point or could you help me to do so?

Best regards,
Philipp

**Comment by Crystalix007** [comment]
See #6.
